import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ur';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.order': 'Order',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'AL-Hani',
    'hero.subtitle': 'Fast Food',
    'hero.tagline': 'Taste That Speaks for Itself!',
    'hero.description': 'Experience the perfect blend of authentic flavors and fast service. From our signature Zinger Burgers to our famous Shapatar Roll, every bite is a celebration!',
    'hero.viewMenu': 'View Menu',
    'hero.orderNow': 'Order Now',
    'hero.newArrival': 'New Arrival',
    'hero.shapatarTitle': 'Shapatar Roll',
    'hero.shapatarDesc': 'Rolled in Foil, 24 Inches of Flavor!',
    'hero.shapatarDetail': 'Our signature creation - a massive 24-inch roll packed with tender meat, fresh vegetables, and our secret sauce.',
    'hero.customerLove': 'Customer Love',
    'menu.title': 'Our Menu',
    'menu.desc': 'Explore our delicious selection of fast food favorites, made fresh and served hot!',
    'menu.all': 'All Items',
    'menu.burgers': 'Burgers',
    'menu.sandwiches': 'Sandwiches',
    'menu.rolls': 'Rolls',
    'menu.pizzas': 'Pizzas',
    'menu.drinks': 'Drinks',
    'menu.specials': 'Specials',
    'menu.noItems': 'No items found in this category.',
    'menu.add': 'Add',
    'menu.seeAll': 'See All Items',
    'order.title': 'Place Your Order',
    'order.desc': 'Add your favorite items to cart and complete your order in seconds!',
    'order.details': 'Delivery Details',
    'order.summary': 'Order Summary',
    'order.name': 'Full Name *',
    'order.phone': 'Phone Number *',
    'order.address': 'Delivery Address *',
    'order.notes': 'Special Instructions (Optional)',
    'order.placeholder.name': 'Enter your name',
    'order.placeholder.phone': '+92 300 1234567',
    'order.placeholder.address': 'Enter complete delivery address',
    'order.placeholder.notes': 'Any special requests?',
    'order.total': 'Total:',
    'order.whatsapp': 'Order via WhatsApp',
    'order.clear': 'Clear Cart',
    'order.empty': 'Your cart is empty',
    'order.success': 'Order Placed Successfully!',
    'order.thanks': 'Thank you for your order. We\'ll deliver your food shortly.',
    'order.backHome': 'Back to Home',
    'order.label.name': 'Name:',
    'order.label.phone': 'Phone:',
    'order.label.total': 'Total:',
    'footer.tagline': 'Taste That Speaks for Itself! Serving delicious fast food with love since 2020.',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact Info',
    'footer.hours': 'Opening Hours',
    'footer.visit': 'Click here to visit live location',
    'footer.days': 'Monday - Sunday',
    'footer.time': '4:00 PM - 4:00 AM',
    'footer.open': 'We\'re Open Every Day!',
    'footer.rights': 'All rights reserved.',
    'about.title': 'About AL-Hani Fast Food',
    'about.subtitle': 'Our Story of Flavor & Excellence',
    'about.journey.title': 'Our Journey',
    'about.journey.p1': 'AL-Hani Fast Food began with a simple vision: to serve delicious, high-quality fast food that brings people together. What started as a small family kitchen has grown into a beloved local favorite, known for our commitment to freshness and flavor.',
    'about.journey.p2': 'Every dish we serve is crafted with care, using the finest ingredients and time-tested recipes. From our signature Zinger Burgers to our innovative Shapatar Roll, we believe that great food should be both fast and exceptional.',
    'about.journey.p3': 'Our success is built on three core principles:',
    'about.fresh': 'Fresh Ingredients',
    'about.fresh.desc': 'We source the freshest items daily to ensure every meal is of the highest quality.',
    'about.service': 'Fast Service',
    'about.service.desc': 'Quick preparation and delivery without compromising on quality or taste.',
    'about.taste': 'Great Taste',
    'about.taste.desc': 'Recipes perfected over years to deliver flavors that keep you coming back.',
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Have questions or feedback? We\'d love to hear from you!',
    'contact.formTitle': 'Send us a Message',
    'contact.name': 'Name *',
    'contact.email': 'Email *',
    'contact.message': 'Message *',
    'contact.placeholder.name': 'Your name',
    'contact.placeholder.email': 'your@email.com',
    'contact.placeholder.message': 'Your message...',
    'contact.whatsapp': 'Send via WhatsApp',
    'contact.location': 'Location',
    'contact.phone': 'Phone',
    'contact.hours': 'Hours',
    'contact.follow': 'Follow Us',
    'contact.emailLabel': 'Email',
    'contact.toastTitle': 'WhatsApp Opened!',
    'contact.toastDesc': 'Complete sending your message in WhatsApp.',
    'modal.price': 'Price',
    'modal.addMore': 'Add more items',
    'modal.checkout': 'Checkout to cart',
    'modal.toastTitle': 'Added to Cart',
    'modal.addedToCart': 'added to your cart.',
    'order.confirmClear': 'Are you sure you want to clear your cart?',
    'order.validation.name': 'Write your full name',
    'order.validation.phone': 'Write your correct phone number',
    'order.validation.address': 'Write your complete address',
    'order.toastEmpty': 'Cart is Empty',
    'order.toastEmptyDesc': 'Please add items to your cart before ordering.',
    'order.toastSuccess': 'Order Processed!',
    'order.toastSuccessDesc': 'WhatsApp message generated and cart cleared.',
    'order.id': 'Order ID:',
    'order.deliveryNote': 'Delivery charges will be according to your location.',
    'hero.featured.zinger': 'Zinger Burger',
    'hero.featured.zingerDesc': 'Crispy & Spicy',
    'hero.featured.club': 'Club Sandwich',
    'hero.featured.clubDesc': 'Triple Decker Delight',
    'hero.featured.shawarma': 'Shawarma Roll',
    'hero.featured.shawarmaDesc': 'Authentic Flavors',
    'hero.featured.pizza': 'Fresh Pizza',
    'hero.featured.pizzaDesc': 'Loaded with Cheese',
    'hero.test1.text': 'Best Zinger in Korangi! The taste is unmatched.',
    'hero.test1.author': 'Ali R.',
    'hero.test2.text': 'The Shapatar Roll is actually huge and delicious! Highly recommended.',
    'hero.test2.author': 'Sana M.',
    'hero.test3.text': 'Fastest delivery service in the area. Food arrives hot every time.',
    'hero.test3.author': 'Usman K.',
    'hero.test4.text': 'Quality ingredients and great value for money. My go-to spot.',
    'hero.test4.author': 'Fatima Z.',
    'hero.test5.text': 'Club Sandwich is a masterpiece. Loaded with flavor!',
    'hero.test5.author': 'Hamza S.',
  },
  ur: {
    'nav.home': 'ہوم',
    'nav.menu': 'مینو',
    'nav.order': 'آرڈر',
    'nav.about': 'ہمارے بارے میں',
    'nav.contact': 'رابطہ',
    'hero.title': 'الحانی',
    'hero.subtitle': 'فاسٹ فوڈ',
    'hero.tagline': 'ذائقہ جو خود بولے!',
    'hero.description': 'اصلی ذائقوں اور بہترین سروس کے امتزاج کا تجربہ کریں۔ ہمارے مشہور زنگر برگر سے لے کر شاہکار شاپاتر رول تک، ہر نوالہ ایک لاجواب ذائقہ ہے!',
    'hero.viewMenu': 'مینو دیکھیں',
    'hero.orderNow': 'ابھی آرڈر کریں',
    'hero.newArrival': 'نئی آمد',
    'hero.shapatarTitle': 'شاپاتر رول',
    'hero.shapatarDesc': 'فوائل میں لپٹا ہوا، 24 انچ کا ذائقہ!',
    'hero.shapatarDetail': 'ہماری خاص پیشکش - ایک بڑا 24 انچ کا رول جو رسیلے گوشت، تازہ سبزیوں اور ہماری مخصوص چٹنی سے بھرپور ہے۔',
    'hero.customerLove': 'گاہکوں کی پسند',
    'menu.title': 'ہمارا مینو',
    'menu.desc': 'ہمارے لذیذ فاسٹ فوڈ مینو سے اپنی پسندیدہ اشیاء کا انتخاب کریں، جو تازہ اور گرما گرم پیش کی جاتی ہیں!',
    'menu.all': 'تمام اشیاء',
    'menu.burgers': 'برگر',
    'menu.sandwiches': 'سینڈوچ',
    'menu.rolls': 'رولز',
    'menu.pizzas': 'پیزا',
    'menu.drinks': 'مشروبات',
    'menu.specials': 'سپیشل',
    'menu.noItems': 'اس زمرے میں کوئی اشیاء موجود نہیں ہیں۔',
    'menu.add': 'شامل کریں',
    'menu.seeAll': 'تمام اشیاء دیکھیں',
    'order.title': 'اپنا آرڈر دیں',
    'order.desc': 'اپنی پسندیدہ اشیاء منتخب کریں اور چند لمحوں میں اپنا آرڈر مکمل کریں!',
    'order.details': 'ڈیلیوری کی معلومات',
    'order.summary': 'آرڈر کی تفصیلات',
    'order.name': 'مکمل نام *',
    'order.phone': 'فون نمبر *',
    'order.address': 'ڈیلیوری کا پتہ *',
    'order.notes': 'خصوصی ہدایات (اختیاری)',
    'order.placeholder.name': 'اپنا نام درج کریں',
    'order.placeholder.phone': 'مثلاً 03001234567',
    'order.placeholder.address': 'ڈیلیوری کا مکمل پتہ درج کریں',
    'order.placeholder.notes': 'کوئی خاص ہدایت؟',
    'order.total': 'کل رقم:',
    'order.whatsapp': 'واٹس ایپ پر آرڈر کریں',
    'order.clear': 'کارٹ صاف کریں',
    'order.empty': 'آپ کی کارٹ خالی ہے',
    'order.success': 'آرڈر کامیابی سے وصول ہو گیا!',
    'order.thanks': 'آرڈر کرنے کا شکریہ۔ ہم جلد ہی آپ کا کھانا پہنچا دیں گے۔',
    'order.backHome': 'ہوم پیج پر واپس جائیں',
    'order.label.name': 'نام:',
    'order.label.phone': 'فون نمبر:',
    'order.label.total': 'ٹوٹل:',
    'footer.tagline': 'ذائقہ جو خود بولے! 2020 سے آپ کی خدمت میں حاضر۔',
    'footer.links': 'فوری روابط',
    'footer.contact': 'رابطہ کی معلومات',
    'footer.hours': 'کھلنے کے اوقات',
    'footer.visit': 'لوکیشن دیکھنے کے لیے یہاں کلک کریں',
    'footer.days': 'پیر سے اتوار',
    'footer.time': 'شام 4:00 بجے سے صبح 4:00 بجے تک',
    'footer.open': 'ہم ہفتے کے ساتوں دن کھلے ہیں!',
    'footer.rights': 'جملہ حقوق محفوظ ہیں۔',
    'about.title': 'الحانی فاسٹ فوڈ کے بارے میں',
    'about.subtitle': 'ذائقہ اور عمدگی کی ہماری کہانی',
    'about.journey.title': 'ہمارا سفر',
    'about.journey.p1': 'الحانی فاسٹ فوڈ کا آغاز ایک سادہ وژن سے ہوا: ایسا لذیذ اور معیاری کھانا پیش کرنا جو لوگوں کے دل جیت لے۔ ایک چھوٹے خاندانی باورچی خانے سے شروع ہونے والا یہ سفر اب علاقے کے ایک مقبول فوڈ پوائنٹ کی صورت اختیار کر چکا ہے، جو اپنی تازگی اور بہترین ذائقے کی وجہ سے مشہور ہے۔',
    'about.journey.p2': 'ہماری ہر ڈش بہترین اجزاء اور آزمودہ ترکیبوں سے تیار کی جاتی ہے۔ ہمارے مخصوص زنگر برگر ہوں یا شاہکار شاپاتر رول، ہمارا مشن بہترین معیار اور لاجواب ذائقہ فراہم کرنا ہے۔',
    'about.journey.p3': 'ہماری کامیابی تین بنیادی اصولوں پر مبنی ہے:',
    'about.fresh': 'تازہ اجزاء',
    'about.fresh.desc': 'ہم روزانہ تازہ ترین اجزاء حاصل کرتے ہیں تاکہ کھانے کے معیار پر کوئی سمجھوتہ نہ ہو۔',
    'about.service': 'تیز سروس',
    'about.service.desc': 'معیار اور ذائقہ برقرار رکھتے ہوئے فوری تیاری اور ڈیلیوری۔',
    'about.taste': 'عمدہ ذائقہ',
    'about.taste.desc': 'برسوں کی محنت سے تیار کردہ ترکیبیں جو آپ کو بار بار آنے پر مجبور کر دیں گی۔',
    'contact.title': 'رابطہ کریں',
    'contact.subtitle': 'کوئی سوال ہو یا اپنی رائے دینا چاہیں؟ ہمیں آپ سے رابطہ کر کے خوشی ہوگی!',
    'contact.formTitle': 'ہم سے رابطہ کریں',
    'contact.name': 'نام *',
    'contact.email': 'ای میل *',
    'contact.message': 'پیغام *',
    'contact.placeholder.name': 'آپ کا نام',
    'contact.placeholder.email': 'آپ کی ای میل',
    'contact.placeholder.message': 'آپ کا پیغام...',
    'contact.whatsapp': 'واٹس ایپ پر بھیجیں',
    'contact.location': 'مقام',
    'contact.phone': 'فون',
    'contact.hours': 'اوقات',
    'contact.follow': 'سوشل میڈیا پر جڑیں',
    'contact.emailLabel': 'ای میل',
    'contact.toastTitle': 'واٹس ایپ کھل گیا!',
    'contact.toastDesc': 'واٹس ایپ پر اپنا پیغام بھیجنا مکمل کریں۔',
    'modal.price': 'قیمت',
    'modal.addMore': 'مزید شامل کریں',
    'modal.checkout': 'کارٹ میں دیکھیں',
    'modal.toastTitle': 'کارٹ میں شامل ہو گیا',
    'order.confirmClear': 'کیا آپ واقعی کارٹ خالی کرنا چاہتے ہیں؟',
    'order.validation.name': 'براہ کرم اپنا مکمل نام درج کریں',
    'order.validation.phone': 'براہ کرم درست فون نمبر درج کریں',
    'order.validation.address': 'براہ کرم مکمل پتہ درج کریں',
    'order.toastEmpty': 'کارٹ خالی ہے',
    'order.toastEmptyDesc': 'آرڈر کے لیے براہ کرم کارٹ میں اشیاء شامل کریں۔',
    'order.toastSuccess': 'آرڈر مکمل ہو گیا!',
    'order.toastSuccessDesc': 'آپ کا آرڈر واٹس ایپ پر تیار ہے، برائے مہربانی اسے بھیج دیں۔',
    'order.id': 'آرڈر آئی ڈی:',
    'order.deliveryNote': 'ڈیلیوری چارجز آپ کی لوکیشن کے مطابق ہوں گے۔',
    'modal.addedToCart': 'کارٹ میں شامل کر دیا گیا ہے',
    'hero.featured.zinger': 'زنگر برگر',
    'hero.featured.zingerDesc': 'کرسپی اور اسپائسی',
    'hero.featured.club': 'کلب سینڈوچ',
    'hero.featured.clubDesc': 'ٹرپل ڈیکر ڈیلائٹ',
    'hero.featured.shawarma': 'شورما رول',
    'hero.featured.shawarmaDesc': 'اصلی ذائقہ',
    'hero.featured.pizza': 'فریش پیزا',
    'hero.featured.pizzaDesc': 'چیزی اور لذیذ',
    'hero.test1.text': 'کورنگی میں بہترین زنگر! ذائقہ واقعی بے مثال ہے۔',
    'hero.test1.author': 'علی خان',
    'hero.test2.text': 'شاپاتر رول واقعی بہت بڑا اور لذیذ ہے! ضرور ٹرائی کریں۔',
    'hero.test2.author': 'سنا ملک',
    'hero.test3.text': 'انتہائی تیز سروس۔ کھانا ہمیشہ گرم اور تازہ ملتا ہے۔',
    'hero.test3.author': 'عثمان غنی',
    'hero.test4.text': 'معیاری اجزاء اور مناسب قیمت۔ میری پسندیدہ جگہ۔',
    'hero.test4.author': 'فاطمہ زہرا',
    'hero.test5.text': 'ان کا کلب سینڈوچ لاجواب ہے۔ ذائقوں سے بھرپور!',
    'hero.test5.author': 'حمزہ شیخ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('alhani-lang');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('alhani-lang', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRtl = language === 'ur';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      <div className={isRtl ? 'font-urdu' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
